/** Generated by scripts/encode-media.mjs — do not edit by hand.
 *
 *  SIZES carries every rendition's REAL pixel dimensions, so the player picks
 *  one by comparing them against the viewport rather than guessing from a
 *  width threshold. A new rendition is picked up automatically.
 *
 *  HAS_WEBM / HAS_WEBM_2K list the clips whose VP9 came out SMALLER than the
 *  H.264 at that size. The two sets are deliberately not the same: VP9 loses
 *  on some of this footage, and a larger "more efficient" file served to
 *  Chrome is a pure loss. */
export type Variant = 'sm' | '@2k';

export const SIZES: Record<string, Partial<Record<Variant, [number, number]>>> =
{
  "bloom": {
    "sm": [
      1280,
      548
    ],
    "@2k": [
      2560,
      1096
    ]
  },
  "latency": {
    "sm": [
      1280,
      548
    ],
    "@2k": [
      2560,
      1096
    ]
  },
  "lumen": {
    "sm": [
      1280,
      548
    ],
    "@2k": [
      2560,
      1096
    ]
  },
  "mesh": {
    "sm": [
      1280,
      548
    ],
    "@2k": [
      2560,
      1096
    ]
  },
  "survey": {
    "sm": [
      1280,
      548
    ],
    "@2k": [
      2560,
      1096
    ]
  },
  "weave": {
    "sm": [
      1280,
      548
    ],
    "@2k": [
      2560,
      1096
    ]
  }
};

export const HAS_WEBM = new Set<string>(["bloom","latency","lumen","mesh","survey","weave"]);
export const HAS_WEBM_2K = new Set<string>(["bloom","latency","lumen","mesh","survey","weave"]);

/** Every clip the build knows about. scripts/check-media.mjs asserts that
 *  every name used in the markup appears here and on disk. */
export const CLIPS = ["bloom","latency","lumen","mesh","survey","weave"] as const;
