/** Generated by scripts/encode-media.mjs — do not edit by hand.
 *
 *  SIZES carries each clip's real pixel dimensions so the player can decide
 *  whether a film is worth loading at all on a given viewport, rather than
 *  guessing from a width threshold.
 *
 *  HAS_WEBM lists the clips whose VP9 came out SMALLER than their H.264.
 *  It is not every clip: VP9 loses on some of this footage, and shipping a
 *  larger "more efficient" file to Chrome is a pure loss. */
export const SIZES: Record<string, [number, number]> = {
  "bloom": [
    1470,
    630
  ],
  "latency": [
    1470,
    630
  ],
  "lumen": [
    1470,
    630
  ],
  "mesh": [
    1470,
    630
  ],
  "survey": [
    1470,
    630
  ],
  "weave": [
    1470,
    630
  ]
};

export const HAS_WEBM = new Set<string>(["bloom","latency","lumen","mesh","survey","weave"]);

/** Every clip the build knows about. scripts/check-media.mjs asserts that
 *  every name used in the markup appears here and on disk. */
export const CLIPS = ["bloom","latency","lumen","mesh","survey","weave"] as const;
